version: '3'

services:
  finance-test:
    image: node:18
    container_name: finance-test
    ports:
      - "3006:3000"
    working_dir: /app
    volumes:
      - ./:/app
    command: node test-server.js